name: google_mlkit_translation
description: Stub package for google_mlkit_translation to enable iOS simulator builds on Apple Silicon.
version: 0.13.0
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
